type TEAM_TRAINER {
  TEAM: [TYPE]
}

type TYPE {
  ID: ID!
  SLOT_NUMBER: Int
  GENERATED_POKEMON: GENERATED_POKEMON
  TRAINER: USERS
}

type Query {
  team(trainerId: ID): [TEAM_TRAINER!]!
}

type Mutation {
  addNewPokeToTeam(generatedPokemonIdBeingAdded: ID, trainerId: ID): [TYPE]!
  changePokemonFromTeam(generatedPokemonIdBeingAdded: ID, slot: Int, trainerId: ID): [TYPE]!
  removeFromTeam(slot: Int, trainerId: ID): [TYPE]!
}
