type GENERATED_POKEMON {
  ID: ID!
  POKEMON: POKEMONS
  HP: Int
  CURRENT_HP: Int
  POKEMON_LEVEL: Int
}

type Query {
  generatedPokemons: [GENERATED_POKEMON!]!
}

type Mutation {
  generatePokemon(pokemonId: ID, mapId: ID): GENERATED_POKEMON
  catchPokemon(
    generatedPokemonId: ID
    pokeballItemId: ID
    trainerId: ID
  ): [Boolean]
}

type Subscription {
  catchingPokemon(trainerId: ID): Boolean
}
