type USERS {
  ID: ID!
  USERNAME: String
  TRAINER: String
  REGION: String
  AGE: Int
  POKEDEX_CAPTURED: Int
  POKEDEX_FOUND: Int
  VICTORIES: Int
  LOSSES: Int
  BAG: [BAG_ITEM]
  TRAINER_POKEMONS: [GENERATED_POKEMON_TRAINER]
  CURRENT_TEAM: TEAM_TRAINER!
}

type BAG_ITEM {
  QTD_ITEM: Int
  ITEM: ITEMS
}

type Query {
  user(id: ID): USERS!
  users: [USERS!]!
  logIn(username: String, password: String): USERS
}

input UserInput {
  age: Int!
  chosenInitial: ID!
  email: String
  password: String!
  region: String
  trainer: String!
  trainerName: String
  username: String!
}

type Mutation {
  createUser(user: UserInput): USERS
}
